// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents the label-policy binding.
public struct DataPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Resource name of this data policy, in the format of
  /// `projects/{project_number}/locations/{location_id}/dataPolicies/{data_policy_id}`.
  public var name: Swift.String = Swift.String()

  /// Type of data policy.
  public var dataPolicyType: DataPolicy.DataPolicyType = DataPolicy.DataPolicyType()

  /// User-assigned (human readable) ID of the data policy that needs to be
  /// unique within a project. Used as {data_policy_id} in part of the resource
  /// name.
  public var dataPolicyId: Swift.String = Swift.String()

  /// Label that is bound to this data policy.
  public var matchingLabel: OneOf_MatchingLabel? = nil

  /// The policy that is bound to this data policy.
  public var policy: OneOf_Policy? = nil

  /// Initialize a new instance of `DataPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataPolicy().with { $0.policyTag = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case policyTag = "policyTag"
    case dataMaskingPolicy = "dataMaskingPolicy"
    case name = "name"
    case dataPolicyType = "dataPolicyType"
    case dataPolicyId = "dataPolicyId"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.dataPolicyType = try container.decode(
      DataPolicy.DataPolicyType.self, forKey: .dataPolicyType)
    self.dataPolicyId = try container.decode(Swift.String.self, forKey: .dataPolicyId)

    var matchingLabel: OneOf_MatchingLabel? = nil
    let matchingLabelCheckAndSet = {
      if matchingLabel != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'matchingLabel'"))
      }
      matchingLabel = $0
    }
    if let policyTag = try container.decodeIfPresent(Swift.String.self, forKey: .policyTag) {
      try matchingLabelCheckAndSet(.policyTag(policyTag))
    }
    self.matchingLabel = matchingLabel

    var policy: OneOf_Policy? = nil
    let policyCheckAndSet = {
      if policy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'policy'"))
      }
      policy = $0
    }
    if let dataMaskingPolicy = try container.decodeIfPresent(
      DataMaskingPolicy?.self, forKey: .dataMaskingPolicy)
    {
      try policyCheckAndSet(.dataMaskingPolicy(dataMaskingPolicy))
    }
    self.policy = policy
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.dataPolicyType, forKey: .dataPolicyType)
    try container.encode(self.dataPolicyId, forKey: .dataPolicyId)

    if let choice = self.matchingLabel {
      switch choice {
      case .policyTag(let value):
        try container.encode(value, forKey: .policyTag)
      }
    }

    if let choice = self.policy {
      switch choice {
      case .dataMaskingPolicy(let value):
        try container.encode(value, forKey: .dataMaskingPolicy)
      }
    }
  }

  /// A list of supported data policy types.
  public enum DataPolicyType: Codable, Equatable, Sendable {
    /// Default value for the data policy type. This should not be used.
    case unspecified
    /// Used to create a data policy for data masking.
    case dataMaskingPolicy
    /// Used to create a data policy for column-level security, without data
    /// masking.
    case columnLevelSecurityPolicy
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .dataMaskingPolicy: return 2
      case .columnLevelSecurityPolicy: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATA_POLICY_TYPE_UNSPECIFIED"
      case .dataMaskingPolicy: return "DATA_MASKING_POLICY"
      case .columnLevelSecurityPolicy: return "COLUMN_LEVEL_SECURITY_POLICY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataPolicyType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATA_POLICY_TYPE_UNSPECIFIED": self = .unspecified
      case "COLUMN_LEVEL_SECURITY_POLICY": self = .columnLevelSecurityPolicy
      case "DATA_MASKING_POLICY": self = .dataMaskingPolicy
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataPolicyType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .dataMaskingPolicy
      case 3: self = .columnLevelSecurityPolicy
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .dataMaskingPolicy: return try container.encode(2)
      case .columnLevelSecurityPolicy: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Label that is bound to this data policy.
  public enum OneOf_MatchingLabel: Codable, Equatable, Sendable {
    /// Policy tag resource name, in the format of
    /// `projects/{project_number}/locations/{location_id}/taxonomies/{taxonomy_id}/policyTags/{policyTag_id}`.
    case policyTag(Swift.String)
  }

  /// The policy that is bound to this data policy.
  public enum OneOf_Policy: Codable, Equatable, Sendable {
    /// The data masking policy that specifies the data masking rule to use.
    indirect case dataMaskingPolicy(DataMaskingPolicy?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.datapolicies.v1.DataPolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
